name: WASM Build

on:
  push:
    branches:
      - main

jobs:
  build-latest:
    name: WASM on Latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: jetli/wasm-pack-action@v0.3.0

      - name: Build WASM
        run: |
          cd web && wasm-pack build --target web --out-dir pkg && cp index.html pkg/ && rm pkg/.gitignore

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: web/pkg
          clean: true
          single-commit: true
